spring:
  application:
    name: mrrs-thirdservice

server:
  port: 10006

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4G8bAn3TdKbvASAinJp9
  accessKeySecret: Tg77YuYniaCyJnNhRztW8D9SxYga1t
  bucketName: mrrs-yuqi



  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mrrs:
  elasticsearch:
    host: 127.0.0.1
    port: 9200

ribbon:
  ReadTimeout=4000   //处理请求的超时时间，默认为1秒
  ConnectTimeout=4000   /  /连接建立的超时时长，默认1秒